version: 2.1

jobs:
  build-and-destroy:
    docker:
      - image: hashicorp/terraform:latest
    working_directory: /Terraform_Final
    steps:
      - checkout
      - run:
          name: Terraform Init
          command: terraform init
      - run:
          name: Terraform Apply
          command: terraform apply -auto-approve

  hold-for-destroy:
    docker:
      - image: hashicorp/terraform:latest
    working_directory: /Terraform_Final
    steps:
      - checkout
      - run:
          name: Hold for Destroy Approval
          command: echo "Hold for manual approval for destroy..."

  destroy:
    docker:
      - image: hashicorp/terraform:latest
    working_directory: /Terraform_Final
    steps:
      - checkout
      - run:
          name: Terraform Init
          command: terraform init
      - run:
          name: Terraform Destroy
          command: terraform destroy -auto-approve


workflows:
  version: 2
  build-and-destroy:
    jobs:
      - build-and-destroy:
          filters:
            branches:
              only:
                - build-branch

      - hold-for-destroy:
          type: approval
          requires:
            - build-and-destroy

      - destroy:
          requires:
            - hold-for-destroy
          filters:
            branches:
              only:
                - build-branch
